name: r-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.43
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - curl=8.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=15.1.0
  - harfbuzz=11.2.1
  - icu=75.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.8.4
  - libglib=2.84.1
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsanitizer=15.1.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - make=4.4.1
  - ncurses=6.5
  - openssl=3.5.0
  - pandoc=3.7.0.1
  - pango=1.56.3
  - pcre2=10.44
  - pixman=0.46.0
  - pthread-stubs=0.4
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-commonmark=1.9.5
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-curl=6.2.2
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-downlit=0.4.4
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.3
  - r-fansi=1.0.6
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-fs=1.6.6
  - r-gert=2.1.4
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-glue=1.8.0
  - r-highr=0.11
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr2=1.1.2
  - r-ini=0.3.1
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-later=1.4.2
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-memoise=2.0.1
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-numbers=0.8_5
  - r-openssl=2.3.2
  - r-pillar=1.10.2
  - r-pkgbuild=1.4.7
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.2
  - r-pkgload=1.4.0
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-profvis=0.4.0
  - r-promises=1.3.2
  - r-ps=1.9.1
  - r-purrr=1.0.4
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcpp=1.0.14
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.2
  - r-rprojroot=2.0.4
  - r-rstudioapi=0.17.1
  - r-rversions=2.1.2
  - r-sass=0.4.10
  - r-sessioninfo=1.2.3
  - r-shiny=1.10.0
  - r-sourcetools=0.1.7_1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-testthat=3.2.3
  - r-textshaping=1.0.1
  - r-tibble=3.2.1
  - r-tinytex=0.57
  - r-urlchecker=1.0.1
  - r-usethis=3.1.0
  - r-utf8=1.2.5
  - r-vctrs=0.6.5
  - r-waldo=0.6.1
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zip=2.3.3
  - readline=8.2
  - sed=4.9
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2025b
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - zstd=1.5.7

